### ISSUE TITLE
 Could not find or load main class

### ISSUE THREAD

**Issue by futureweb** [idrm/create-panono-backup#2]
Hello,
I just tried to get the Backup-Script to work - but unfortunately I alwas get the Error "Could not find or load main class" ... ?

See Screenshot:
![grafik](https://cloud.githubusercontent.com/assets/1698881/26578748/727059e6-4531-11e7-9622-828f9a8f74ce.png)

Any ideas on that? ;-)

Thank you, bye from Austria
Andreas Schnederle-Wagner

**Comment by idrm** [comment]
Which version of Java are you running it with?
If you're on Java 8 or above, can you try the [previous version](http://radiatic.com/create-panono-backup-1.1.2.jar)?

**Comment by futureweb** [comment]
```
Q:\PanonoBackups>java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

Unfortunately the same Problem with 1.1.2 Version: 
`Fehler: Hauptklasse create-panono-backup-1.1.2.jar konnte nicht gefunden oder geladen werden`

**Comment by idrm** [comment]
Ah, I see the issue. You need to add a `-jar` option before the jar file name.

**Comment by futureweb** [comment]
you nailed it! ;-)

See Pull Request ;-)

**Comment by idrm** [comment]
Thanks! I hadn't realized I removed that from the README.

**Comment by futureweb** [comment]
thx for super-fast help on this! 👍
