### ISSUE TITLE
Error on Backup

### ISSUE THREAD

**Issue by futureweb** [idrm/create-panono-backup#5]
Hey there,
just tried to Backup our second Panono Account - but unfortunately I get this Error:

> 
> Q:\PanonoBackups>java -jar create-panono-backup-1.2.1.jar --username "panono3@rundblick.at" --password "MyPass" --includeUpf yes --timestampedFolders yes
> Fetching panoramas with offset [-]
> !!! Request to https://api3-dev.panono.com/u/panono3%40rundblick.at/panoramas?pageSize=12 returned status code 404
> Response: HttpResponseProxy{HTTP/1.1 404 Not Found [Access-Control-Allow-Credentials: true, Access-Control-Allow-Origin: https://cloud.panono.com, Content-Type: application/json; charset=utf-8, Date: Tue, 27 Jun 2017 07:31:41 GMT, Vary: Accept-Encoding, Vary: Origin, Connection: keep-alive] org.apache.http.client.entity.DecompressingEntity@7a8c8dcf}
> Failed to fetch panoramas: Fetch panoramas request error (#3): Fetch panoramas request error (#2): {"code":404,"message":"404: Not Found","success":false}
> Found 0 non-synced panoramas out of 0 total
> Could not write the panoramas.txt file
> Done backing up Panono panoramas

Any Ideas on that? (70 Panos are uploaded on that Account)

Thank you
Andreas

**Comment by idrm** [comment]
You seem to be using an older version of the app. Try the latest one.

**Comment by futureweb** [comment]
ops - overlooked there is a 1.3 already - sorry! ;-)
